---
title: "Assignment 3 (HW #3)"
subtitle: "Nuclear Energy Infographic"
description: "Assigned Tue 02/11/2025 | Due Tue 02/25/2025"
author: "Kaiju Morquecho"
toc: true
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE}
# Load libraries 
library(here)
library(dplyr) 
library(ggplot2)
library(janitor)
library(png)
library(jpeg)
library(patchwork)
library(scico)
library(tidyverse)
library(htmltools)
library(ggrepel)
library(grid)
library(scales)
library(stringr)
library(lubridate)
library(ggimage)
library(ggfx)
library(scales)
library(gghighlight)
library(ggtext)
library(sysfonts)
library(magick)
library(showtext)
```

## Enable showtext_auto()
```{r}
# enable showtext 
showtext_auto()
```

## Load fonts

```{r}
font_add_google(name = "Keania One", family = "ko")
font_add_google(name = "Smooch Sans", family = "ss")
```

# Load data
```{r}
chernobyl_exposure <-read.csv(here("data","chernobyl_exposure_distance.csv")) %>%
  clean_names()

chernobyl_water <- read.csv(here("data","chernobyl_water_chem.csv")) %>%
  clean_names()

nuclear_accidents <- read.csv(here("data","nuclear_accidents.csv") ) %>%
  clean_names() 
```

# Wrangle Chernobyl exposure rate data 
```{r}
# drop NA's 
chernobyl_exposure <- chernobyl_exposure %>%
  filter(!is.na(exposure_dose_rate_m_r_h)) 

# find average absorbed doses at km intervals
km_intervals <- chernobyl_exposure %>%
  
  filter(distance_from_ch_npp_km %in% c(5,10, 20, 30, 50, 60)) %>%
  
  arrange(desc(absorbed_dose_rate_micro_gray_h)) %>%
  
  group_by(distance_from_ch_npp_km) %>%
  
  slice_head(n = 1) %>%
  
  filter(!distance_from_ch_npp_km == 20) %>%
  
  mutate(comparison = paste0(  # assuming 1 chest xray = 0.1 mGy
  
    "PEAK RADIATION DOSE: ", absorbed_dose_rate_micro_gray_h, " MGY / HR",
    "\nOR ", absorbed_dose_rate_micro_gray_h/0.1, " CHEST X-RAYS PER HR", sep = " ")) %>% 
  
  ungroup()


km_intervals$location <-c(-0.9,-0.9,-0.9,-0.9)

```

# Wrangle nuclear accidents data
```{r}
# filter to INES levels of interest 
nuclear_accidents <- nuclear_accidents %>%
  filter(ines_level >= 4) %>% # filter to accidents of INES level 4-7
  filter(!is.na(ines_level)) %>%  # drop if ines_level = NA
  mutate(description = paste(incident, location, sep = ",\n "))


# make "date" col into date object, set "orders" to all possible date formats in the df
nuclear_accidents$date <- year(as.Date(parse_date_time(nuclear_accidents$date, orders =  c("m/d/Y","d/m/Y"))))


```

```{r}
# add nuclear symbol to df
nuclear_accidents$image <- rep(c(here("samples","nuclear_symbol.png")), 10)

# name background image object

background <- "https://miro.medium.com/v2/resize:fit:4800/format:webp/1*hL391IqaaorQv-c5-a5w-w.jpeg"

# heights for milestones.
nuclear_accidents$positions <- c(0.13, -0.1, 0.09, -0.05, .05, -.1, .09, -.05, .05, -.05) 

# set the directions for each accident, aka above and below timeline
nuclear_accidents$directions <- c(1, -1) 

```

# Create timeline of nuclear accidents

```{r}

timeline <- ggplot(nuclear_accidents, aes(x = date, y = positions, label = description)) +
  theme_classic() +
  
  # horizontal timeline
  with_outer_glow(
    
    geom_hline(yintercept = 0,
             color = "springgreen",
             alpha = 0.9,
             linejoin = "round",
             linewidth = 3,
             show.legend = FALSE),
    
    
    colour = "springgreen",
    sigma = 2,
    expand = 1) +
  
  # lines conencting accident to timeline
  with_outer_glow(
    
    
    geom_segment(data = nuclear_accidents, aes(y = positions,
                                             yend = 0,
                                             xend = date),
                 linewidth = 1,
                 color = "springgreen"),
    
    
    colour = "springgreen",
    sigma = 2,
    expand = 0.5) +
  
  # year labels on timeline
  geom_label(aes(x = date, 
                label = date,
                y = 0),
             fill = "black",
             color = "white",
             family = "ss",
             size = 7,
             show.legend = FALSE) +

  geom_point(aes(y = positions), size = 1) +

  
  # text boxes that are html friendly, accident description
  geom_textbox(aes(label = str_wrap(
    
    paste0("<b><span style='color:black;'>",incident,".</b>", tags$br(), location))),
    fill = "white",
    color = "black",
    size = 5,
    
    family = "ss",
    width = 0.2,
    halign = 0.5,
    valign = 0.5,
    show.legend = TRUE
              ) +
  
  labs(title = "AT A GLANCE: HISTORY OF NUCLEAR ACCIDENTS",
       subtitle = "The International Nuclear and Radiological Event Scale (INES) is a logarithmic scale with 7 levels. Levels 4-7 are reserved for high-impact accidents") +
  
  
  theme(
        plot.title = element_text(family = "ko",
                                  margin = margin(t = 0, r = 0, b = 10 , l = 0, unit = "pt"),
                                  size = 30,
                                  color = "springgreen"),
        plot.subtitle = element_text(family = "ss",
                                     size = 20,
                                     color = "white",
                                     margin = margin(t = 0, r = 0, b = 30 , l = 0, unit = "pt")),
        plot.title.position = "plot",
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.line.y = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks = element_blank(),
        axis.title.x = element_blank(),
        axis.line.x = element_blank(),
        # legend.direction = "horizontal",
        # legend.position = "bottom",
        panel.background = element_rect(fill = "black"),
        plot.background = element_rect(fill = "black"),
        plot.margin = margin(t = 70, r = 100, b = 70, l = 100, unit = "pt")) +
  
  
   coord_cartesian(clip = "off")


# timeline <- ggbackground(timeline, background, alpha = 0.1)

ggsave("timeline.png",
       plot = timeline,
       device = "png",
       width = 10, 
       height = 12,
       units = "cm",
       dpi = 300
       )

timeline 

```

# Create raster grobs 
```{r}
# save power plant image path + warning sign path
plant_path <- here("samples", "design.png")

warning_path <- here("samples","warning.png")


# read as PNG
plant <- readPNG(plant_path, native = FALSE)

warning <- readPNG(warning_path, native = FALSE)

# turn to raster grob
plant_grob <- rasterGrob(plant,
                         width = unit(4, "cm"), 
                         height = unit(5,"cm"),
                         x = unit(0, "npc"),  
                         y = unit(0, "npc"), 
                         just = c("left", "center")) 
                    

warning_grob <- rasterGrob(warning,
                         width = unit(1, "cm"), 
                         x = unit(0, "npc"),  
                         y = unit(0, "npc"), 
                         just = c("left", "center")) 
                    
```


# Create Exposure Data Viz
```{r}
# make main plot
exposure<- ggplot(chernobyl_exposure, aes(
  y = 0.5,  
  x = distance_from_ch_npp_km,
  fill = absorbed_dose_rate_micro_gray_h
)) +
  
  with_outer_glow(
    
    geom_tile(width = 7.5, height = 0.7, color = "white", show.legend = FALSE),
                  sigma = 2,
                  expand = 8,
                  colour = "springgreen"
    
                  ) +  
    
  scale_fill_gradientn(
    
    colours = c("springgreen", "deeppink", "firebrick2"),
    name = "Absorbed Dose Rate\n(mGy/h)",
    transform = "sqrt"
    
  ) +
  
 scale_x_continuous(
   breaks = seq(0, 60, by = 15),
  labels = paste0(seq(0, 60, by = 15), " km"),
  minor_breaks = seq(0, 60, by = 7.5)
  ) +

  labs(
    
    title = "Radiation Exposure By Proximity To Chernobyl Nuclear Power Plant (NPP)",
    
    subtitle = "According to measurements taken between January 1987 & June 1987 (approximately one year after the accident),\nthe radiation levels 5km away from the power plant were still so high that spending 24 hrs there would likely be lethal.",
    
    x = NULL,
    
    y = NULL,
    
    caption = "Source: CDC, EPA, and Data.Gov.UK Find Open Data."
  ) +
  
  theme_minimal(base_family = "ss") +
  
  theme(
    plot.background = element_rect(fill = "black", color = NA),
    panel.background = element_rect(fill = "black", color = NA),
    panel.grid = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.line = element_blank(),
    plot.title.position = "plot",
    plot.caption.position = "plot",
    plot.caption = element_text(family = "ss",
                                color = "white",
                                size = 15,
                                hjust = 0,
                                face = "italic"),
    
    plot.title = element_text(
      color = "springgreen", 
      size = 30, 
      family = "ko",
      margin = margin(t = 10, r = 0, l = 0, unit = "pt")
    ),
    
    plot.subtitle = element_text(
    color = "white", 
      size = 20, 
      family = "ss",
      margin = margin(t = 10, r = 0, l = 0, unit = "pt")
    ),
    
    plot.margin = margin(t = 50, r = 0, b = 100, l = 50, unit = "pt")
    
  ) +
  
  coord_cartesian(clip = "off", ylim = c(-1.8, 1.5), xlim = c(0,65))

```
  
```{r}
exposure_annotated <- exposure + 
  
    annotation_custom(  
    
    plant_grob,
    xmin = -6,  
    xmax = 4,   
    ymin = 0.6,  
    ymax = 1.8) +
  
  
    annotate( 
    "text",
    x = -3,
    y = -0.1,
    size = 6,
    label = "0 KM",
    family = "ko",
    color = "white"
    ) +
  
  
  geom_segment(
    aes(
    x = 2.9, xend = 63, y = 0.5, yend = 0.5),  
    size = 27, 
    color = "gray30", 
    lineend = "square"
    
  ) +
  
  geom_segment(
    
    aes(x = 2.2, xend = 63, y = 0.5, yend = 0.5),
    linetype = "dashed",
    color = "gold2",
    size = 2
    
  ) +
  
  geom_curve(
  data = km_intervals,
  aes(
    x = distance_from_ch_npp_km - 3.5,
    y = -0.5,
    xend = distance_from_ch_npp_km - 3.75,
    yend = 0.1
  ),
  curvature = -0.3, 
  color = "white",
  linewidth = 0.7,
  arrow = arrow(length = unit(0.25, "cm"), type = "closed")
) +

  
  geom_label(data = km_intervals, 
  aes( # data on each km interval
    x = distance_from_ch_npp_km - 4,
    y =  location,
    label = paste0(
    absorbed_dose_rate_micro_gray_h / 0.1, " Chest X-Rays/Hr", sep ="")), 
  color = "white",
  fill = "black",
  size = 6,
  hjust = 0,
  nudge_x = c(-5,-0.3,-0.3,-0.3),
  inherit.aes = FALSE,
  family = "ss") +
  
  with_outer_glow(
    
    annotation_custom(  # warning sign for 5km mark
    
    warning_grob,
    xmin = km_intervals$distance_from_ch_npp_km[1] - 4,  
    xmax = km_intervals$distance_from_ch_npp_km[1] - 4,   
    ymin = 0.5,  
    ymax = 0.7
  ),
  
  sigma = 2,
  expand = 2, 
  colour = "springgreen"
  ) +
  
  with_outer_glow(
    
    annotation_custom(  # warning sign for 10km mark
    
    warning_grob,
    xmin = km_intervals$distance_from_ch_npp_km[2] - 4,  
    xmax = km_intervals$distance_from_ch_npp_km[2] - 4,   
    ymin = 0.5,  
    ymax = 0.7
    
  ),

   sigma = 2,
  expand = 2, 
  colour = "springgreen"
  )+
  
  with_outer_glow(
    
    annotation_custom(  # warning sign for 30km mark
    
    warning_grob,
    xmin = km_intervals$distance_from_ch_npp_km[3] - 4,  
    xmax = km_intervals$distance_from_ch_npp_km[3] - 4,   
    ymin = 0.5,  
    ymax = 0.7
    
  ),
  
   sigma = 2,
  expand = 2, 
  colour = "springgreen"
  )+
  
   with_outer_glow( 
     
    annotation_custom(  # warning sign for 60km mark
    warning_grob,
    xmin = km_intervals$distance_from_ch_npp_km[4] - 4,  
    xmax = km_intervals$distance_from_ch_npp_km[4] - 4,   
    ymin = 0.5,  
    ymax = 0.7
    
  ),
  
   sigma = 2,
  expand = 2, 
  colour = "springgreen"
   ) +
  
  geom_text(data = km_intervals,  # km markers
  aes(x = distance_from_ch_npp_km - 2.75, y = -0.7, 
  label = paste0(distance_from_ch_npp_km, "KM", sep = " ")), 
  color = "white", 
  family = "ko",
  size = 6)+

  theme(text = element_text(family = "ss")) 

exposure_annotated
```

# Create water contamination data viz 
```{r}

water <- ggplot(chernobyl_water, aes(x = distance_from_cnpp_km, y = x137cs_deposition_k_bq_m2)) +
  
  # trend line with glow
  with_outer_glow(
    geom_smooth(method = "loess", se = FALSE, color = "deeppink", size = 1.5),
    colour = "deeppink",
    sigma = 5,
    expand = 1
  ) +
  
    # lakes as points
  with_outer_glow(
    geom_point(size = 2, color = "white"),
    colour = "deeppink",
    sigma = 3,
    expand = 3
  ) +

  scale_y_continuous(trans = "sqrt") +
  
  # Labels
  labs(
    title = "Radioactive Cesium-137 Deposition",
    subtitle = "Distance from Chernobyl NPP vs Deposition (kBq/m²)",
    x = "Distance from Chernobyl NPP (km)",
    y = "Cs-137 Deposition (kBq/m²)"
  ) +

  theme(
    plot.background = element_rect(fill = "black", color = NA),
    panel.background = element_rect(fill = "black", color = NA),
    panel.grid = element_line(colour = "springgreen",
                              linewidth = 0.1),
    
    axis.title = element_text(color = "white", size = 14, family = "ss"),
    axis.text = element_text(color = "white", size = 12, family = "ss"),
    
    plot.title = element_text(color = "springgreen", size = 20, family = "ko"),
    plot.subtitle = element_text(color = "white", size = 14, family = "ss"),
    
    plot.margin = margin(1, 1, 1, 1, "cm")
  )

ggsave("chernobyl_water_glow.png", plot = water, width = 10, height = 6, dpi = 300)

water
```
